//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace Naftan.VatInvoices.Mnsati.Additional {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3schools.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3schools.com", IsNullable=false)]
    public partial class issuance {
        
        /// <remarks/>
        public general general;
        
        /// <remarks/>
        public rosterList roster;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sender;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class  general {
        
        /// <remarks/>
        public string number;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dateIssuance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dateTransaction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTransactionSpecified;
        
        /// <remarks/>
        public invoiceDocType documentType;
        
        /// <remarks/>
        public string invoice;
        
        /// <remarks/>
        public bool sendToRecipient;
        
        public general() {
            this.sendToRecipient = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public enum invoiceDocType {
        
        /// <remarks/>
        ORIGINAL,
        
        /// <remarks/>
        ADDITIONAL,
        
        /// <remarks/>
        FIXED,
        
        /// <remarks/>
        ADD_NO_REFERENCE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class vat {
        
        /// <remarks/>
        public decimal rate;
        
        /// <remarks/>
        public rateType rateType;
        
        /// <remarks/>
        public decimal summaVat;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public enum rateType {
        
        /// <remarks/>
        DECIMAL,
        
        /// <remarks/>
        ZERO,
        
        /// <remarks/>
        NO_VAT,
        
        /// <remarks/>
        CALCULATED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class rosterItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string number;
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string code_oced;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string units;
        
        /// <remarks/>
        public decimal count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified;
        
        /// <remarks/>
        public decimal price;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified;
        
        /// <remarks/>
        public decimal cost;
        
        /// <remarks/>
        public decimal summaExcise;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool summaExciseSpecified;
        
        /// <remarks/>
        public vat vat;
        
        /// <remarks/>
        public decimal costVat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("description", IsNullable=false)]
        public descriptionType[] descriptions;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public enum descriptionType {
        
        /// <remarks/>
        DEDUCTION_IN_FULL,
        
        /// <remarks/>
        VAT_EXEMPTION,
        
        /// <remarks/>
        OUTSIDE_RB,
        
        /// <remarks/>
        IMPORT_VAT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3schools.com")]
    public partial class rosterList {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rosterItem")]
        public rosterItem[] rosterItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal totalCostVat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal totalExcise;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal totalVat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal totalCost;
    }
}
